# Generated by Django 4.2.13 on 2024-12-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
